### ISSUE TITLE
Support busway

### ISSUE THREAD

**Issue by AgusQui** [geofabrik/osmi_pubtrans3#13]
Add support to new tagging of BRTs: highway=busway [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway](url), and thus avoid the error_over_rail.

**Comment by A67-A67** [comment]
In the Netherlands we're keeping the public transport routes clean of errors thanks to OSM Inspector. Thanks a lot for this application!

The lack of support of the highway=busway is starting to be a problem, as people are adding those and all bus lines using those busways are falsely seen as erroneous by OSM Inspector. 

I think this can be solved easily by changing line 92 of file /src/ptv2_checker.cpp to
`|| !strcmp(highway, "living_street") || !strcmp(highway, "bus_guideway")  || !strcmp(highway, "busway")`

**Comment by Famlam** [comment]
Thanks!
If I may be so bold to ask: could it be correct that this change isn't live on the web interface yet?

**Comment by woodpeck** [comment]
The change will be live on the web interface tomorrow (~ 16 hours from now).

**Comment by A67-A67** [comment]
It seems the change is still not visible on the [web interface](https://tools.geofabrik.de/osmi/). The many invalid bus routes in the Netherlands are mostly due to the error 'road vehicle route over non-road' on a road tagged as highway=busway.

So either 38fe5b23b0e5e18669e2e8704a414530524c3e7a isn't the full solution to this issue, or the change isn't live on the web interface yet.

**Comment by A67-A67** [comment]
It seems to be solved now. Thank you very much!
