### ISSUE TITLE
Please, nake check for "trolley bus without trolley wire" optional

### ISSUE THREAD

**Issue by iav** [geofabrik/osmi_pubtrans3#14]
Now I see in my city error "error: | trolley bus without trolley wire"
http://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=24.22763&lat=56.98671&zoom=15&overlays=ptv2_error_,ptv2_error_ways,ptv2_error_nodes

It is true. But it's not an error: there used trolleybuses with diesel or hydrogen second engine, and part of routes they goes without wires.
Then I'd like to have a way to uncheck this type of error.

**Comment by Nakaner** [comment]
Making the check optional requires to add a new layer in the OSMI frontend. If we added a new layer for a special type of error, it is just a question of time until someone requests another error to be optional. Broken routs often have multiple errors. They would be rendered on multiple layers and therefore slow down rendering if they are rendered twice or more for the same map view. That's why I prefer not to make the check optional.

Instead, I suggest to invent a tag to distinguish hybrid from non-hybrid trolleybuses, i.e. if a trolleybus regularly uses sections without trolley wire, a tag on the route should indicate that. I could disable the check for these routes by default. You are free to discuss this idea on the [Tagging](https://lists.openstreetmap.org/listinfo/tagging) or [Talk-transit](https://lists.openstreetmap.org/listinfo/talk-transit) mailing list.

**Comment by szjozsef** [comment]
I think #9 is the solution for this

**Comment by iav** [comment]
Yes.
Thank you.
