### ISSUE TITLE
Add support for light_rail routes

### ISSUE THREAD

**Issue by dobratzp** [geofabrik/osmi_pubtrans3#2]
Currently, routes using [route=light_rail](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dlight_rail) are flagged with the `unknown_route_type` error in the "Public Transport - Routes" layer of [OSM Inspector](http://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=-122.95908&lat=45.51707&zoom=15&overlays=ptv2_routes_,ptv2_routes_valid,ptv2_routes_invalid,ptv2_error_,ptv2_error_ways,ptv2_error_nodes).  Can support for light_rail be added?

**Comment by Nakaner** [comment]
`light_rail` is no valid route type in the tagging scheme which is implemented by this validator. `light_rail=yes` and `route=light_rail` were added after the end of voting to the wiki page and the change (there was even a small edit war) should be reverted. [This](https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Public_Transport&oldid=625726) is the official final and voted version of the proposal/tagging scheme.

**Comment by ghost** [comment]
Openstreetmap's wiki refers to use of route=light_rail
https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes

There are numerous routes using route=light_rail.  What are these supposed be classified as?

**Comment by urbalazs** [comment]
Light rail is used 845 times based on the wiki: https://wiki.openstreetmap.org/wiki/Tag:route%3Dlight_rail
Please reopen this issue and add this route type to the validator.

**Comment by Yogurt4** [comment]
I second ghost. According to the OSM Wiki it's a valid route type.
The above referenced proposal is from 2011 and a lot have happened since.

Or what else is the suggested solution? To tag it as "route=train"? Or tag it as "route=tram"? It's neither, hence its own [railway=light_rail](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlight_rail) tag. By the way, even this Wiki page suggests making a light_trail route.

**Comment by Nakaner** [comment]
This validator uses a relatively strict approach. Therefore, `light_rail` is not supported for `route=*`. If a proposal will make `light_rail` valid again, I will add support to the validator. (It is likely that I will vote in favour of such a proposal)

> Or what else is the suggested solution? To tag it as "route=train"? Or tag it as "route=tram"? It's neither, hence its own railway=light_rail tag. By the way, even this Wiki page suggests making a light_trail route.

I know lots of routes which could fit into the light rail category here in Germany. Some of them use `train`, others use `tram`. That's the recommendation. It depends on the character. Some even use `subway`:

* If it is a tram-train system/line, i.e. vehicles run on tram/light-rail tracks and normal train tracks (some share tracks with ICE trains!), we usually use `train`. We even use `train` if the line runs through pedestrian areas like in Karlsruhe.
* If it is a mix of subway and tram because they started replacing the tram by a subway in the 1960s to 1980s but ran out of money and still use tram-ish or partially tram-ish vehicles in subway tunnels and on the street, we use `tram` or `subway`. This depends on the floor level of the vehicle (low entry vs high entry) and how good the overground sections are separated from traffic.
