### ISSUE TITLE
Route inspector does not recognize roundabout=circular

### ISSUE THREAD

**Issue by blef00fr** [geofabrik/osmi_pubtrans3#27]
Route inspector does not recognize roundabout=circular #24 has been closed on Jan 30, 2023 but the issue still remains.
See [exemple](https://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=8.63025&lat=50.17640&zoom=17&baselayer=Geofabrik%20Standard&overlays=ptv2_routes_invalid%2Cptv2_error_ways%2Cptv2_error_nodes) from #24 and also [here](https://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=-0.93901&lat=43.39975&zoom=19&baselayer=Geofabrik%20Standard&overlays=ptv2_routes_%2Cptv2_routes_valid%2Cptv2_routes_invalid%2Cptv2_error_%2Cptv2_error_ways%2Cptv2_error_nodes).

**Comment by gosgtan** [comment]
I got same the issue with a few routes since the last data update a few hours ago, everything was perfectly fine beforehand. It seems like there are issues with false "road vehicle route over non-road" and "Street vehicle route over railways" errors. Appeared today but relations haven't been changed by anyone since months

**Comment by blef00fr** [comment]
Everything seems to be back to normal

**Comment by blef00fr** [comment]
Everything seems to be back to normal
